### ISSUE TITLE
Containerize CeeBee

### ISSUE THREAD

**Issue by FBoucher** [FBoucher/CloudBot#42]
To project the chatbot while working with Node on other project.

**Comment by FBoucher** [comment]
Nice progress it's mostly working.
Presently the command `!attention` fail. We need to install the font (or default on a local one)

```
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Error: ENOENT: no such file or directory, open './public/medias/generated/2020-11-26-1205_Att-fboucheros.png'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at createImage (/usr/src/app/index.js:142:8)
    at /usr/src/app/index.js:47:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
```
